### ISSUE TITLE
rss support?

### ISSUE THREAD

**Issue by MartijnR** [onaio/blog#2]
Can't seem to be able to add this as a feed to feedly.com. Not sure if RSS support is the only solution. 

I still think RSS rocks...:(

**Comment by urbanslug** [comment]
I've done this in a other static site generators but not with Jekyll, it's just generating an xml file. I will look into this.

**Comment by urbanslug** [comment]
Hmmm there's a feed button on the blog which leads to an xml file. @rowo maybe this should be closed?

**Comment by pld** [comment]
yep, looks good

https://feedly.com/i/spotlight/http://blog.ona.io/
