### ISSUE TITLE
Find template options for Blog Change Recommendations

### ISSUE THREAD

**Issue by COpenda** [onaio/blog#66]
1. Creating categories
-Ona Releases
-Best practices
-Ona Impact 
-What's happening 
-Inside Ona
-Opinions and discussions

2. Navigation buttons
-Categories should be visible, for users to easily navigate to other related articles
-Show related and recent posts
- include search button
-include social media (share) buttons after every article
- Include CTA to get free account 
-Freeze the menu bar to make it easier to navigate back to the main 

3. Layout and design
-Show snippets of recent articles and their image 
-Do away with the banner image
-Enable commenting and likes and shares

@rowo

**Comment by rowo** [comment]
@COpenda I'd recommend looking at Jekyll templates to see which match up to your above recommendations. If you can't find one, we can explore changing platforms, especially with the scheduling posts (https://github.com/onaio/blog/issues/67) being not straightforward.

**Comment by COpenda** [comment]
@rowo had a look at the jekyll themes and "Feeling Responsive" could be the one.

**Comment by rowo** [comment]
Link?

**Comment by COpenda** [comment]
http://jekyllthemes.org/themes/feeling-responsive/ @rowo

**Comment by rowo** [comment]
Seems fine to me. I don't think our blog has to match with the main site. Did you see anything else that was good or is this clearly the top choice?

**Comment by COpenda** [comment]
That's my top choice because it has everything i'm keen on and even things like disqus and it's ability to show snippets of various articles, related posts, categories....another close one is http://jekyllthemes.org/themes/sciblog/

**Comment by rowo** [comment]
Created https://github.com/onaio/blog/issues/71 for implementation
