### ISSUE TITLE
Scheduling posts Function

### ISSUE THREAD

**Issue by COpenda** [onaio/blog#67]
Please enable post scheduling on the blog. We have a lot of content to share based on out content strategy, we need to be able to manage this.
@rowo

**Comment by rowo** [comment]
https://talk.jekyllrb.com/t/cant-figure-out-how-to-schedule-future-posts/2042/2

@mberg @pld know anything about Jekyll for scheduling posts?

**Comment by pld** [comment]
Sort of, guess is to put a future published date in and ta-da!?

**Comment by rowo** [comment]
@pld yeah I think that works. Can you do option 2 from [this website](http://www.fizerkhan.com/blog/posts/Working-with-upcoming-posts-in-Jekyll.html) to the config file? I don't want to break it.

Then @COpenda can try it.

**Comment by rowo** [comment]
this is not possible. should we switch to wordpress @mberg?
