### ISSUE TITLE
Ona R blog post and user story

### ISSUE THREAD

**Issue by COpenda** [onaio/blog#80]
- Get an Ona R user story to merge into a post
- support guide to go up on the help site for referencing.
- Ref this [issue](https://github.com/onaio/help/issues/152)

**Comment by rowo** [comment]
Is this the same as https://github.com/onaio/blog/pull/88 ? Is the reference material up?

**Comment by pld** [comment]
I don't know, I haven't seen this issue before

**Comment by COpenda** [comment]
Yes it is the same @pld @rowo closing this
